name: flutter_web_browser
description: A flutter plugin project to open a web page with Chrome Custom Tabs & SFSafariViewController.
homepage: https://github.com/victorbonnet/flutter_web_browser
version: 0.16.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.vbonnet.flutterwebbrowser
        pluginClass: FlutterWebBrowserPlugin
      ios:
        pluginClass: FlutterWebBrowserPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
